"""Deploy 节点：容器部署和健康检查

负责 ContainerLab 拓扑的部署、权限修复和容器健康检查。
"""
import subprocess
import os
import time
from typing import Dict, Any, Tuple, Optional

from clab_builder.state import GraphState
from clab_builder.config import config
from clab_builder.logger import get_logger, set_log_context, log_step, log_error
from .fixer import ERROR_TYPE_DEPLOY, ERROR_TYPE_SYSTEM
from .utils import ConfigApplier


def generate_redeploy_script(yaml_path: str, json_path: str, config_dir: str, needs_sudo: bool) -> str:
    """生成redeploy脚本

    Args:
        yaml_path: clab.yml文件路径
        json_path: config.json文件路径
        config_dir: 配置文件目录
        needs_sudo: 是否需要sudo

    Returns:
        生成的脚本文件路径
    """
    logger = get_logger("node.deploy")

    yaml_basename = os.path.basename(yaml_path)
    yaml_filename = os.path.splitext(yaml_basename)[0]
    lab_name = os.path.splitext(yaml_basename)[0].replace('.clab', '')
    json_name = os.path.basename(json_path)  # 获取JSON文件名

    # 生成redeploy脚本
    script_path = os.path.join(config_dir, f"redeploy.sh")

    sudo_prefix = "sudo " if needs_sudo else ""

    script_content = f"""#!/bin/bash
# ContainerLab Redeploy Script
# Generated by containerlab-builder
# Lab: {lab_name}

set -e  # 遇到错误立即退出

SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
YAML_FILE="${{SCRIPT_DIR}}/{yaml_basename}"

echo "=========================================="
echo "🔄 ContainerLab Redeploy"
echo "=========================================="
echo "Lab: {lab_name}"
echo "YAML: $YAML_FILE"
echo ""

# 步骤1: 销毁现有部署
echo "📦 Step 1: Destroying existing deployment..."
{sudo_prefix}containerlab destroy -t "$YAML_FILE" --cleanup || echo "⚠️  No existing deployment to destroy"
echo "✓ Destroy completed"
echo ""

# 步骤2: 重新部署
echo "🚀 Step 2: Redeploying containers..."
{sudo_prefix}containerlab deploy -t "$YAML_FILE" --reconfigure
echo "✓ Deploy completed"
echo ""

# 步骤3: 等待容器启动
echo "⏳ Step 3: Waiting for containers to be ready..."
sleep 3
echo "✓ Containers ready"
echo ""

# 步骤4: 应用网络配置
echo "🌐 Step 4: Applying network configuration..."

# 从config.json读取配置并应用
python3 << 'PYEOF'
import sys
import os
import json
import subprocess

def get_container_pid(node_name, lab_name):
    '获取容器PID'
    try:
        container_name = f"clab-{{lab_name}}-{{node_name}}"
        result = subprocess.run(
            ["docker", "inspect", "-f", "{{{{.State.Pid}}}}", container_name],
            capture_output=True,
            text=True,
            timeout=10,
            check=True
        )
        return int(result.stdout.strip())
    except:
        return None

def nsenter_exec(pid, command):
    '使用nsenter执行命令(忽略IP已存在的错误)'
    if not pid:
        return False
    try:
        full_cmd = f"sudo nsenter -n -t {pid} -- {command}"
        subprocess.run(full_cmd, shell=True, check=True, capture_output=True, timeout=30)
        return True
    except subprocess.CalledProcessError as e:
        # IP地址已存在不是错误
        stderr = e.stderr.decode() if e.stderr else ""
        if "File exists" in stderr or "RTNETLINK answers: File exists" in stderr:
            return True  # IP已配置，视为成功
        return False
    except:
        return False

# 读取配置
config_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), "{json_name}")

try:
    with open(config_file, 'r') as f:
        config = json.load(f)

    lab_name = config['lab_name']
    success_count = 0
    failed_nodes = []

    for node_name, node_config in config["nodes"].items():
        role = node_config.get("role", "")

        # 跳过switch节点
        if role == "switch":
            continue

        pid = get_container_pid(node_name, lab_name)
        if not pid:
            failed_nodes.append(node_name)
            continue

        node_success = True

        # 配置IP地址
        if "interfaces" in node_config:
            for iface in node_config["interfaces"]:
                iface_name = iface["name"]
                address = iface["address"]

                if not nsenter_exec(pid, f"ip addr add {address} dev {iface_name}"):
                    node_success = False

                if not nsenter_exec(pid, f"ip link set dev {iface_name} up"):
                    node_success = False

        # 配置默认路由
        if "default_route" in node_config:
            route = node_config["default_route"]
            gateway = route.get("gateway")

            if gateway and not nsenter_exec(pid, f"ip route replace default via {gateway}"):
                node_success = False

        if node_success:
            success_count += 1
        else:
            failed_nodes.append(node_name)

    total = len([n for n, c in config["nodes"].items() if c.get("role") != "switch"])
    print(f"✓ Configuration complete: {success_count}/{total} nodes")

    if failed_nodes:
        print(f"⚠️  Failed nodes: {', '.join(failed_nodes)}")

    sys.exit(0)

except Exception as e:
    print(f"✗ Configuration failed: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)
PYEOF

CONFIG_EXIT=$?

if [ $CONFIG_EXIT -eq 0 ]; then
    echo "✓ Network configuration applied successfully"
else
    echo "⚠️  Some network configurations failed"
    echo "   You may need to configure manually"
fi
echo ""

echo "=========================================="
echo "✅ Redeploy completed!"
echo "=========================================="
echo ""
echo "📊 Next steps:"
echo "  - Check containers: docker ps | grep clab"
echo "  - View logs: docker logs <container-name>"
echo "  - Access topology: containerlab inspect -t $YAML_FILE"
"""

    # 写入脚本
    with open(script_path, 'w') as f:
        f.write(script_content)

    # 设置可执行权限
    os.chmod(script_path, 0o755)

    log_step(
        logger,
        f"Redeploy script generated: {script_path}",
        status="success"
    )

    return script_path


# 检测是否需要 sudo（全局缓存一次）
_NEEDS_SUDO: Optional[bool] = None


def check_containerlab_needs_sudo() -> bool:
    """检查执行 containerlab 是否需要 sudo。

    Returns:
        True 如果需要 sudo，否则 False
    """
    global _NEEDS_SUDO

    if _NEEDS_SUDO is not None:
        return _NEEDS_SUDO

    logger = get_logger("node.deploy")
    logger.debug("Checking if containerlab requires sudo...")

    try:
        subprocess.run(
            ["containerlab", "version"],
            capture_output=True,
            timeout=5,
            check=True
        )
        _NEEDS_SUDO = False
        logger.debug("containerlab can run without sudo")
        return False
    except (subprocess.CalledProcessError, FileNotFoundError, Exception) as e:
        logger.debug(f"containerlab requires sudo: {e}")
        _NEEDS_SUDO = True
        return True


def get_sudo_prefix() -> str:
    """获取 sudo 前缀。

    Returns:
        "sudo " 如果需要 sudo，否则 ""
    """
    return "sudo " if check_containerlab_needs_sudo() else ""


def run_command_streaming(
    cmd: str,
    timeout: int = None,
    logger: Optional[Any] = None
) -> Tuple[int, str]:
    """
    执行命令并实时打印输出（Streaming Output）。

    防止长时间无响应被误判为卡死，提供实时进度反馈。

    Args:
        cmd: 要执行的命令
        timeout: 超时时间（秒），None 则使用配置默认值
        logger: logger 实例

    Returns:
        (return_code, full_output) 元组
    """
    if logger is None:
        logger = get_logger("node.deploy")

    if timeout is None:
        timeout = config.timeout_seconds

    logger.info(f"⚙️  Executing: {cmd}")

    try:
        process = subprocess.Popen(
            cmd,
            shell=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
    except Exception as e:
        log_error(logger, e, "Failed to start command process")
        return -1, f"Failed to start process: {str(e)}"

    full_output = []
    start_time = time.time()

    if process.stdout is None:
        process.wait()
        return process.returncode, "Error: stdout is None"

    last_progress_time = start_time
    progress_interval = 30

    try:
        while True:
            elapsed = time.time() - start_time
            if elapsed > timeout:
                process.kill()
                logger.warning(f"Command timeout after {elapsed:.1f}s")
                return -1, "".join(full_output) + f"\n[Timeout after {elapsed:.1f}s]"

            if elapsed - (last_progress_time - start_time) > progress_interval:
                logger.debug(f"Command still running... ({elapsed:.1f}s elapsed)")
                last_progress_time = time.time()

            line = process.stdout.readline()
            if not line and process.poll() is not None:
                break

            if line:
                logger.debug(f"   | {line.strip()}")
                full_output.append(line)

    except KeyboardInterrupt:
        logger.warning("Command interrupted by user")
        process.kill()
        return -1, "".join(full_output) + "\n[Interrupted by user]"

    return process.returncode, "".join(full_output)


def wait_for_lab_healthy(
    yaml_path: str,
    logger: Optional[Any] = None
) -> Tuple[bool, Optional[Dict]]:
    """
    异步轮询：主动检查 inspect 状态，直到所有容器都 Running。

    Args:
        yaml_path: YAML 文件路径
        logger: logger 实例

    Returns:
        (is_healthy, inspect_data) 元组
    """
    if logger is None:
        logger = get_logger("node.deploy")

    max_retries = config.container_health_check_max_retries
    interval = config.container_health_check_interval
    sudo_prefix = get_sudo_prefix()

    log_step(logger, "Waiting for containers to become healthy", status="start")

    for attempt in range(max_retries):
        cmd = f"{sudo_prefix}containerlab inspect -t {yaml_path} --format json"

        try:
            res = subprocess.run(
                cmd,
                shell=True,
                capture_output=True,
                text=True,
                timeout=30
            )
        except subprocess.TimeoutExpired:
            logger.warning(f"Inspect command timeout (attempt {attempt + 1}/{max_retries})")
            time.sleep(interval)
            continue

        if res.returncode == 0:
            try:
                data = __import__("json").loads(res.stdout)

                # 提取容器列表
                containers = []
                for value in data.values():
                    if isinstance(value, list):
                        containers = value
                        break

                if not containers:
                    logger.warning(
                        f"Inspect returned valid JSON but no containers found "
                        f"(attempt {attempt + 1}/{max_retries})"
                    )
                    if attempt == 0:
                        logger.debug(f"Raw output: {res.stdout[:200]}...")
                    time.sleep(interval)
                    continue

                not_ready = [c['name'] for c in containers if c['state'].lower() != 'running']

                if not not_ready:
                    log_step(
                        logger,
                        "All containers healthy",
                        status="success",
                        total_containers=len(containers)
                    )
                    return True, data
                else:
                    logger.debug(
                        f"Waiting for {len(not_ready)}/{len(containers)} containers: "
                        f"{', '.join(not_ready[:3])}{'...' if len(not_ready) > 3 else ''}"
                    )
            except __import__("json").JSONDecodeError as e:
                logger.error(f"JSON decode error (attempt {attempt + 1}/{max_retries}): {e}")
                logger.debug(f"Raw output: {res.stdout[:200]}...")
        else:
            logger.warning(
                f"Inspect command failed (rc={res.returncode}, attempt {attempt + 1}/{max_retries})"
            )
            if res.stderr:
                logger.debug(f"stderr: {res.stderr[:200]}")

        time.sleep(interval)

    log_step(
        logger,
        "Container health check timeout",
        status="fail",
        max_retries=max_retries
    )
    return False, None


def deploy(state: GraphState) -> Dict[str, Any]:
    """
    Deploy 节点：部署容器实验室并进行健康检查。

    工作流程:
    1. 预清理（destroy 已有的 lab）
    2. 流式部署（实时输出进度）
    3. 健康检查（等待所有容器 running）
    4. 应用网络配置（使用 JSON + ConfigApplier）

    Args:
        state: 当前工作流状态

    Returns:
        更新后的状态字典
    """
    logger = get_logger("node.deploy")
    set_log_context(stage="deploy")

    yaml_path = os.path.abspath(state['yaml_path'])
    json_path = state.get('json_path')
    sudo_prefix = get_sudo_prefix()

    log_step(logger, f"Deploying {yaml_path}", status="start")

    if check_containerlab_needs_sudo():
        logger.debug("Using sudo for containerlab commands")

    # =========================================
    # 步骤 1: 预清理（快速清理）
    # =========================================
    log_step(logger, "Pre-cleaning existing deployment", status="start")
    logger.debug("Pre-cleaning existing deployment...")
    try:
        subprocess.run(
            f"{sudo_prefix}containerlab destroy -t {yaml_path} --cleanup",
            shell=True,
            capture_output=True,
            timeout=60
        )
        log_step(logger, "Pre-clean completed", status="success")
    except Exception as e:
        logger.debug(f"Pre-clean warning (non-critical): {e}")
        log_step(logger, "Pre-clean skipped (no existing deployment)", status="success")

    # =========================================
    # 步骤 2: 流式部署
    # =========================================
    log_step(logger, "Deploying containers with containerlab", status="start")
    return_code, logs = run_command_streaming(
        f"{sudo_prefix}containerlab deploy -t {yaml_path} --reconfigure",
        timeout=config.timeout_seconds,
        logger=logger
    )

    if return_code != 0:
        # 判断是系统错误还是部署错误
        error_lower = logs.lower()
        if any(keyword in error_lower for keyword in [
            "permission denied", "access denied", "operation not permitted",
            "no space left", "disk full", "out of memory", "oom",
            "docker daemon", "docker not running"
        ]):
            error_type = ERROR_TYPE_SYSTEM
        else:
            error_type = ERROR_TYPE_DEPLOY

        # 截断日志（避免 token 过多）
        error_logs_short = logs[-2000:] if len(logs) > 2000 else logs

        logger.error(f"Error logs (will be sent to fixer):\n{error_logs_short}")

        log_step(
            logger,
            "Deployment failed",
            status="fail",
            return_code=return_code
        )

        return {
            "error_logs": f"{error_type} {error_logs_short}",
            "is_deployed": False,
            "inspect_data": None
        }

    log_step(logger, "Containers deployed successfully", status="success")

    # =========================================
    # 步骤 3: 健康检查
    # =========================================
    is_healthy, inspect_data = wait_for_lab_healthy(yaml_path, logger=logger)

    if not is_healthy:
        error_msg = (
            "Timeout waiting for containers to become 'running'. "
            "Check the container logs for issues."
        )
        log_step(logger, "Health check failed", status="fail")
        return {
            "error_logs": f"{ERROR_TYPE_DEPLOY} {error_msg}",
            "is_deployed": False,
            "inspect_data": None
        }

    # =========================================
    # 步骤 5: 应用网络配置
    # =========================================
    if json_path:
        log_step(logger, "Applying network configuration", status="start")

        try:
            # 提取 lab_name（去除 .clab.yml 后缀）
            lab_name = os.path.basename(yaml_path).replace('.clab.yml', '')
            config_dir = os.path.dirname(json_path)

            logger.debug(f"Applying network config for lab: {lab_name}")
            logger.debug(f"Config directory: {config_dir}")

            # 直接使用 ConfigApplier 类
            applier = ConfigApplier(lab_name, config_dir)
            stats = applier.apply_all()

            if stats["failed"] == 0:
                log_step(
                    logger,
                    "Network configuration applied successfully",
                    status="success",
                    configured=stats["success"]
                )
            else:
                log_step(
                    logger,
                    "Network configuration completed with warnings",
                    status="success",
                    configured=stats["success"],
                    failed=stats["failed"]
                )
                logger.warning(f"Failed nodes: {', '.join(stats['failed_nodes'])}")

        except FileNotFoundError as e:
            log_error(logger, e, "Config file not found (non-critical)")
        except Exception as e:
            log_error(logger, e, "Failed to apply network configuration (non-critical)")
            # 不中断部署流程，只记录错误

    log_step(logger, "Deployment completed successfully", status="success")

    # =========================================
    # 步骤 6: 生成redeploy脚本
    # =========================================
    try:
        redeploy_script = generate_redeploy_script(
            yaml_path=yaml_path,
            json_path=json_path,
            config_dir=config_dir,
            needs_sudo=check_containerlab_needs_sudo()
        )
        logger.info(f"📜 Redeploy script: {redeploy_script}")
    except Exception as e:
        log_error(logger, e, "Failed to generate redeploy script (non-critical)")

    return {
        "error_logs": "",
        "is_deployed": True,
        "inspect_data": inspect_data
    }
