frr version 8.5
frr defaults traditional
hostname router-2
no ipv6 forwarding
!
interface lo
 ip address 10.10.2.1/32
!
interface eth1
 ip address 10.0.1.2/24
!
interface eth2
 ip address 10.0.2.1/24
!
router ospf
 ospf router-id 10.10.2.1
 passive-interface eth0
 network 10.0.1.0/24 area 0
 network 10.0.2.0/24 area 0
!