frr version 8.5
frr defaults traditional
hostname aggregation-router-01
no ipv6 forwarding
!
interface lo
 ip address 10.10.4.1/32
!
interface eth1
 ip address 10.0.3.2/24
!
interface eth2
 ip address 10.0.4.1/24
!
router ospf
 ospf router-id 10.10.4.1
 passive-interface eth0
 network 10.0.3.0/24 area 0
 network 10.0.4.0/24 area 0
!