import os
import yaml
import ipaddress
import shutil
from collections import defaultdict
from typing import Dict, Any, List,Literal, Union

from pydantic import BaseModel, Field

class LogicalNode(BaseModel):
    name: str = Field(..., description="Unique hostname. MUST be lowercase, kebab-case (e.g., 'edge-router'). NO spaces, underscores, or special characters.")
    role: Literal["router", "endpoint", "switch"] = Field(..., description="The functional role of the node.")
    image_flavor: str = Field(..., description="Abstract flavor: 'kali', 'alpine', 'redis', 'log4j-vuln', etc.")
    connected_subnets: List[str] = Field(..., description="List of subnet names this node connects to. e.g. ['dmz', 'internal'].")

class NetworkBlueprint(BaseModel):
    """The logical intent generated by the LLM."""
    lab_name: str = Field(..., description="Name of the lab. MUST use kebab-case (e.g., 'mvp-pentest-lab'). STRICTLY NO SPACES.")
    complexity: Literal["simple", "medium", "complex"] = Field(..., description="Complexity level. 'complex' triggers FRR/OSPF.")
    subnets: List[str] = Field(..., description="List of unique logical subnet names defined in the topology.")
    nodes: List[LogicalNode] = Field(..., description="List of logical nodes.")

class NetworkBuilder:
    def __init__(self, blueprint: NetworkBlueprint, output_dir: str = "./clab_out"):
        self.bp = blueprint
        self.output_dir = output_dir
        
        # Output structures
        self.clab_nodes: Dict[str, Any] = {}
        self.clab_links: List[Dict[str, Any]] = []
        
        # IPAM State
        self.supernet = ipaddress.IPv4Network("10.0.0.0/8")
        self.subnet_iterator = self.supernet.subnets(new_prefix=24)
        self.subnet_map: Dict[str, ipaddress.IPv4Network] = {} 
        self.node_ip_map: Dict[str, Dict[str, str]] = defaultdict(dict) # {node: {subnet: ip}}
        
        # Initialize workspace
        if os.path.exists(self.output_dir):
            shutil.rmtree(self.output_dir)
        os.makedirs(self.output_dir)

    def build(self) -> str:
        """Main build process. Returns the path to the generated YAML."""
        self._allocate_subnets()
        self._process_topology()
        self._generate_static_routes()
        yaml_content = self._generate_yaml_structure()
        
        filename = f"{self.output_dir}/{self.bp.lab_name}.clab.yml"
        with open(filename, "w") as f:
            yaml.dump(yaml_content, f, sort_keys=False)
        
        return filename

    def _allocate_subnets(self):
        """Assign real CIDRs to logical subnet names."""
        for name in self.bp.subnets:
            self.subnet_map[name] = next(self.subnet_iterator)

    def _determine_image(self, flavor: str, role: str) -> tuple[str, bool]:
        """Maps abstract flavors to real Docker images and checks if tools are needed."""
        flavor = flavor.lower()
        
        # Complex Router -> FRR
        if self.bp.complexity == "complex" and role == "router":
            return "frr/frr:v8.5.1", False
        
        # Simple Router -> Alpine
        if role == "router":
            return "alpine:latest", False
            
        # Switch -> Alpine
        if role == "switch":
            return "alpine:latest", False

        # Endpoints mapping
        if "kali" in flavor: return "kalilinux/kali-rolling:latest", True
        if "log4j" in flavor: return "vulfocus/log4j2-rce-2021-12-09:latest", True # Use fixed date version
        if "redis" in flavor: return "redis:7-alpine", False
        if "alpine" in flavor: return "alpine:latest", False
        
        # Default fallthrough
        return "alpine:latest", False

    def _process_topology(self):
        # Group nodes by subnet to detect where switches are needed
        subnet_members = defaultdict(list)
        for node in self.bp.nodes:
            for sub in node.connected_subnets:
                subnet_members[sub].append(node)

        # 1. Create Nodes
        for node in self.bp.nodes:
            self._create_clab_node(node)

        # 2. Handle Connectivity (Switches & Links & IPs)
        for sub_name, members in subnet_members.items():
            self._wire_subnet(sub_name, members)

    def _create_clab_node(self, node):
        image, needs_tools = self._determine_image(node.image_flavor, node.role)
        
        node_def = {
            "kind": "linux",
            "image": image,
            "exec": [],
            "binds": [],
            "sysctls": {}
        }

        # Pre-install tools for bare images (Kali/Ubuntu/Debian)
        if needs_tools:
            node_def['exec'].append("apt-get update && apt-get install -y iproute2 iputils-ping net-tools")

        # Enable forwarding for routers/switches
        if node.role in ["router", "switch"]:
            node_def['sysctls'] = {"net.ipv4.ip_forward": "1"}
            
        # Specific FRR handling for complex routers
        if self.bp.complexity == "complex" and node.role == "router":
            # FRR capabilities
            node_def["cap_add"] = ["NET_ADMIN", "SYS_ADMIN"]
            # We don't use 'exec' for IP config in FRR, we use config files.
            # But we still create the node structure here.

        self.clab_nodes[node.name] = node_def

    def _wire_subnet(self, subnet_name: str, members: List[Any]):
        """
        Connects members of a subnet. 
        If > 2 members, injects a Switch-in-a-Container.
        """
        cidr_obj = self.subnet_map[subnet_name]
        
        # Determine L2 topology
        if len(members) > 2:
            # Create Switch
            sw_name = f"sw-{subnet_name}"
            self._inject_switch_node(sw_name)
            
            # Connect everyone to switch
            for member in members:
                self._create_link(member.name, sw_name)
        
        elif len(members) == 2:
            # Point-to-Point
            self._create_link(members[0].name, members[1].name)
            
        # Assign IPs logic
        router_host = 1
        client_host = 10
        
        for member in members:
            # Allocate IP
            if member.role == "router":
                ip_str = str(cidr_obj[router_host])
                router_host += 1
            else:
                ip_str = str(cidr_obj[client_host])
                client_host += 1
            
            self.node_ip_map[member.name][subnet_name] = ip_str
            
            # --- Configuration Injection ---
            
            # Case A: Complex Router (FRR) -> Deferred to file generation
            if self.bp.complexity == "complex" and member.role == "router":
                pass # Configs generated later
                
            # Case B: Simple/Medium Node -> Inject 'ip addr' commands
            else:
                # We need to determine interface name (eth1, eth2...)
                # Simplified: assume sequential based on link order. 
                # In prod, we track link counts. Here, we blindly append.
                # A robust way is to use 'ip addr add ... dev $(ls /sys/class/net | grep eth | tail -1)' hack 
                # or verify link count. For MVP, let's assume specific order or use wildcard?
                # BETTER: Use Containerlab's deterministic naming: eth1, eth2...
                # We need to track how many links this node has so far.
                iface_idx = self._get_interface_count(member.name)
                iface_name = f"eth{iface_idx}"
                
                cmd = f"ip addr add {ip_str}/24 dev {iface_name}"
                self.clab_nodes[member.name]['exec'].append(cmd)
                
                # Add Default Route (if endpoint)
                if member.role == "endpoint":
                    gateway = str(cidr_obj[1]) # Assume router is always .1
                    self.clab_nodes[member.name]['exec'].append(f"ip route replace default via {gateway}")

    def _generate_static_routes(self):
        """
        为简单/中等复杂度的网络计算静态路由。
        算法逻辑：
        1. 找出所有路由器。
        2. 对于每个路由器 A，找出它 *没有* 直连的子网。
        3. 找出通往那个子网的邻居路由器 B。
        4. 添加路由: ip route add {target_subnet} via {neighbor_ip}
        """
        
        # 仅针对 Simple/Medium 模式 (Complex 模式由 FRR OSPF 自动处理)
        if self.bp.complexity == "complex":
            return

        # 1. 建立路由表映射: RouterName -> {ConnectedSubnets}
        router_subnets = {}
        router_ips = {} # RouterName -> {SubnetName: IP}
        
        for node in self.bp.nodes:
            if node.role == "router":
                router_subnets[node.name] = set(node.connected_subnets)
                router_ips[node.name] = self.node_ip_map[node.name]

        # 2. 遍历所有路由器，填补路由表
        for r_name, r_connected in router_subnets.items():
            # 遍历所有子网
            for subnet_name, cidr_obj in self.subnet_map.items():
                subnet_cidr = str(cidr_obj)
                
                # 如果这个子网我已经直连了，跳过
                if subnet_name in r_connected:
                    continue
                
                # 如果不直连，我需要找到谁连了这个子网（目标路由器）
                # 寻找同时连接了 "我的直连网段" 和 "目标网段" 的路由器（下一跳）
                # 这是一个简化的线性/星型查找。对于复杂网状，必须用 FRR。
                
                next_hop_ip = None
                
                # 遍历其他路由器作为潜在的下一跳
                for potential_nh_name, nh_connected in router_subnets.items():
                    if potential_nh_name == r_name: continue
                    
                    # 如果这个潜在下一跳直连了目标网段
                    if subnet_name in nh_connected:
                        # 检查我和这个下一跳是否有共同的网段（即我们是否直连）
                        common_subnets = r_connected.intersection(nh_connected)
                        if common_subnets:
                            # 找到了！下一跳 IP 就是它在共同网段里的 IP
                            common_sub = list(common_subnets)[0]
                            next_hop_ip = router_ips[potential_nh_name][common_sub]
                            break
                
                # 生成路由命令
                if next_hop_ip:
                    cmd = f"ip route add {subnet_cidr} via {next_hop_ip}"
                    # 避免重复添加
                    if cmd not in self.clab_nodes[r_name]['exec']:
                        self.clab_nodes[r_name]['exec'].append(cmd)

  

    def _inject_switch_node(self, name):
        """Injects an Alpine-based Linux Bridge."""
        if name not in self.clab_nodes:
            self.clab_nodes[name] = {
                "kind": "linux",
                "image": "alpine:latest",
                "sysctls": {"net.ipv4.ip_forward": "1"},
                "exec": [
                    "apk add --no-cache bridge-utils",
                    "brctl addbr br0",
                    "ip link set dev br0 up"
                    # 'brctl addif' commands will be added when links are created ideally,
                    # or we can use a loop script inside the container.
                    # Simplified: We assume eth1...ethN need to be added.
                ]
            }

    def _create_link(self, node_a, node_b):
        self.clab_links.append({"endpoints": [f"{node_a}:eth{self._inc_interface(node_a)}", 
                                              f"{node_b}:eth{self._inc_interface(node_b)}"]})
        
        # If one is a switch, add logic to attach interface to bridge
        for n in [node_a, node_b]:
            if n.startswith("sw-"):
                iface_id = self._get_interface_count(n)
                cmd = f"brctl addif br0 eth{iface_id} && ip link set dev eth{iface_id} up"
                self.clab_nodes[n]['exec'].append(cmd)

    # --- Helper: Interface Counting ---
    def _interface_tracker(self):
        if not hasattr(self, '_iface_counts'):
            self._iface_counts = defaultdict(int)
        return self._iface_counts

    def _inc_interface(self, node):
        t = self._interface_tracker()
        t[node] += 1
        return t[node]

    def _get_interface_count(self, node):
        return self._interface_tracker()[node]

    # --- FRR Config Generation (Complex Mode) ---
    def _generate_frr_configs(self):
        for name, node_def in self.clab_nodes.items():
            # Check if it corresponds to a complex router
            # We look up in blueprint nodes
            bp_node = next((n for n in self.bp.nodes if n.name == name), None)
            if bp_node and bp_node.role == "router" and self.bp.complexity == "complex":
                
                config_path = os.path.join(self.output_dir, name)
                os.makedirs(config_path, exist_ok=True)
                
                # 1. Generate daemons
                with open(os.path.join(config_path, "daemons"), "w") as f:
                    f.write("zebra=yes\nospfd=yes\n")
                
                # 2. Generate frr.conf
                lines = [
                    "frr version 8.5", "frr defaults traditional", 
                    f"hostname {name}", "no ipv6 forwarding", "!"
                ]
                
                # Loopback
                lines.extend(["interface lo", " ip address 10.10.10.1/32", "!"])
                
                # Interfaces
                # We need to map subnets to interface names again. 
                # This requires tracking which subnet mapped to which interface index.
                # For this snippet, let's assume the node_ip_map iteration order matches link creation.
                # (In production code, you strictly link interface names to subnets).
                
                current_eth = 1
                connected_subs = self.node_ip_map[name]
                for sub_name, ip in connected_subs.items():
                    lines.extend([
                        f"interface eth{current_eth}",
                        f" ip address {ip}/24",
                        "!"
                    ])
                    current_eth += 1

                # OSPF
                lines.extend([
                    "router ospf",
                    " ospf router-id 10.10.10.1",
                    " network 0.0.0.0/0 area 0", # Lazy OSPF
                    "!"
                ])
                
                with open(os.path.join(config_path, "frr.conf"), "w") as f:
                    f.write("\n".join(lines))
                
                # Add binds to node definition
                abs_path = os.path.abspath(config_path)
                node_def['binds'] = [
                    f"{abs_path}/daemons:/etc/frr/daemons",
                    f"{abs_path}/frr.conf:/etc/frr/frr.conf"
                ]

    def _prune_empty(self, data) -> Any:
        """
        递归清除字典和列表中的空值 ([], {}, None)。
        保留 0 和 False，因为它们可能是有效的配置值 (如 ip_forward: 0)。
        """
        if isinstance(data, dict):
            new_dict = {}
            for k, v in data.items():
                cleaned_v = self._prune_empty(v)
                # 关键逻辑：如果值不是 None，且不等于 空列表/空字典，则保留
                # 注意：这里不能简单用 "if cleaned_v"，因为 0 也是 False
                if cleaned_v is not None and cleaned_v != [] and cleaned_v != {}:
                    new_dict[k] = cleaned_v
            return new_dict
        
        elif isinstance(data, list):
            # 处理列表中的每一项
            return [self._prune_empty(item) for item in data]
        
        else:
            # 基本数据类型直接返回
            return data

    def _generate_yaml_structure(self) -> Dict[str, Any]:
        # Post-processing for FRR
        raw_structure= {
            "name": self.bp.lab_name,
            "topology": {
                "nodes": self.clab_nodes,
                "links": self.clab_links
            }
        }
        if self.bp.complexity == "complex":
            self._generate_frr_configs()
        return self._prune_empty(raw_structure)